# Generated by Django 5.0.1 on 2026-06-28 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installment_group',
            field=models.UUIDField(blank=True, null=True, verbose_name='grupo de parcelas'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='parcela atual'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='total de parcelas'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_installment',
            field=models.BooleanField(default=False, verbose_name='parcelado'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='paga'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Salário', 'Salário'), ('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Lazer', 'Lazer'), ('Moradia', 'Moradia'), ('Saúde', 'Saúde'), ('Educação', 'Educação'), ('Outros', 'Outros')], max_length=100, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=255, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
