# Generated by Django 5.0.1 on 2026-06-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_seed_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'transação', 'verbose_name_plural': 'transações'},
        ),
    ]
