# Generated by Django 5.0.1 on 2026-06-29 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_category_options_alter_transaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='arquivo')),
                ('filename_original', models.CharField(max_length=255, verbose_name='nome original')),
                ('filesize', models.IntegerField(verbose_name='tamanho (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.transaction', verbose_name='transação')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
